version: 2
updates:
  - package-ecosystem: "composer"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
