imports:
    - { resource: ../openconext/*.yaml }

framework:
    secret: '%app_secret%'
    csrf_protection: true
    http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    assets: ~
    esi: false
    fragments: false
    php_errors:
        log: "%kernel.debug%"

when@dev:
    framework:
        router:
            strict_requirements: true
        profiler: { only_exceptions: false }

        php_errors:
            log: false
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

when@test:
    framework:
        test: ~
        session:
            storage_id: session.storage.mock_file
        profiler:
            collect: false
        router:
            strict_requirements: true
