imports:
    - { resource: ../openconext/*.yaml }

framework:
    secret: '%app_secret%'
    csrf_protection: true
    http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    assets: ~
    esi: false
    fragments: false
    php_errors:
        log: "%kernel.debug%"

