Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder "..", "/opt/tiqr"

  # forward from localhost port 8080, for talking to tiqr clients through a TLS reverse proxy
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # share the host Internet connection, for talking to tiqr clients directly over http
  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ntp apache2 libapache2-mod-php php-dom php-gd
    # SSL is useful only when using a valid TLS certificate
    a2enmod ssl
    a2ensite default-ssl.conf
    # Otherwise, use a TLS reverse proxy with a valid certificate and a http vhost, see 000-default.conf
    service apache2 reload
  SHELL
end
