imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

# The monolog configuration below overwrites the in logging.yml that
# is normally used for production.
monolog:
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: DEBUG # DEV setting: this means that all message of level DEBUG or higher are always logged
            #passthru_level: NOTICE # PROD setting this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: true
        main_syslog:
            type: syslog
            ident: stepup-tiqr
            facility: user
            formatter: surfnet_stepup.monolog.json_formatter
        main_logfile:
            type: stream
            handler: logfile
            level: NOTICE
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        console:
            type: console
            process_psr_3_messages: false

surfnet_saml:
    hosted:
        identity_provider:
            enabled: true
            service_provider_repository: surfnet_saml.remote.service_providers
            sso_route: gssp_saml_sso
            public_key: "%saml_idp_publickey%"
            private_key: "%saml_idp_privatekey%"
        service_provider:
            enabled: true
            assertion_consumer_route: sp_demo_acs
            public_key: "%saml_idp_publickey%"
            private_key: "%saml_idp_privatekey%"
        metadata:
            entity_id_route: gssp_saml_metadata
            public_key: "%saml_metadata_publickey%"
            private_key: "%saml_metadata_privatekey%"
    remote:
        service_providers:
            - entity_id: "%saml_remote_sp_entity_id%"
              certificate_file: "%saml_remote_sp_certificate%"
              assertion_consumer_service_url: "%saml_remote_sp_acs%"
            - entity_id: https://tiqr.example.com/app_dev.php/saml/metadata
              certificate_file: "%saml_idp_publickey%"
              assertion_consumer_service_url: https://tiqr.example.com/app_dev.php/demo/sp/acs
