app:
    resource: '@AppBundle/Controller/'
    type: annotation

gssp_saml:
    resource: '@SurfnetGsspBundle/Resources/config/routing.yml'

openconext_monitor:
    resource:   "@OpenConextMonitorBundle/Resources/config/routing.yml"
    prefix:     /
