monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            passthru_level: notice # this means that all message of level NOTICE or higher are always logged
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
