imports:
    - { resource: 'services.yaml' }
    - { resource: 'services_dev.yaml' }

services:
    Dev\FileLogger:
        public: true
        decorates: 'logger'
        arguments:
            - '@kernel'

    overide_matcher:
        class: App\Service\UserAgentMatcher
        public: true
        decorates: App\Service\UserAgentMatcher
        arguments:
            - '/^Behat UA$/'

    surfnet_gssp.value_store.service:
        class: Surfnet\GsspBundle\Service\ValueStore\InMemoryValueStore
        public: true
