services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Surfnet\Tiqr\Dev\:
        resource: '../dev/*'
        exclude: '../dev/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Surfnet\Tiqr\Dev\Controller\:
        resource: '../dev/Controller'
        tags: ['controller.service_arguments']
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: Symfony\Component\HttpClient\HttpClient
        factory: ['Surfnet\Tiqr\Dev\HttpClientFactory', 'create']
