# Create user & group for FPM pool
- name: Add group {{ app_name }}
  group: name={{ app_name }} state=present

- name: Add user {{ app_name }}
  user: name={{ app_name }} group={{ app_name }} createhome=no state=present

- name: Create directory for vhosts to store PHP sessions
  file: path=/var/lib/stepup/session/{{ app_name }} state=directory owner={{ app_name }} group=root mode=770
  become: true

# Put httpd vhost config
- name: Create ssl
  include_role:
    name: openmicroscopy.nginx-ssl-selfsigned

- name: Put httpd vhost config for {{ vhost_name }}
  action: template src='nginx-vhost.conf.j2' dest='/etc/nginx/conf.d/{{ vhost_name }}.conf'
  notify:
    - restart nginx

# Put fpm config
- name: php-fpm config
  template: src='php-fpm-pool.conf.j2' dest='/etc/php-fpm.d/{{ vhost_name }}.conf'
  notify:
    - restart php-fpm

- name: Put rsyslog vhost config
  template: src='rsyslog_nginx_vhost.conf.j2' dest='/etc/rsyslog.d/nginx_vhost_{{ app_name }}.conf'
  notify:
    - restart rsyslog
