#!/usr/bin/env bash

cd $(dirname $0)/../../

printf "\nStart application Linting\n"
#Lints PHP,yml,ts,tsc and composer.json
./vendor/bin/phplint --no-ansi -n --no-progress --configuration=ci/qa/phplint.yaml $1

bin/console lint:yaml config
yarn eslint -c ./.eslintrc.js
yarn tsc --noEmit
