#!/usr/bin/env bash

cd $(dirname $0)/../../

printf "\nStart PHPUnit tests\n"
XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration=ci/qa/phpunit.xml --cache-result-file=../../var/cache/.phpunit-cache --coverage-text
